name: GraalVM Native with Kotlin and Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Add msbuild to PATH
      if: ${{ matrix.platform == 'windows-latest' }}
      uses: microsoft/setup-msbuild@v1.0.1 # https://github.com/marketplace/actions/setup-msbuild
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Validate the Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache the GraalVM distribution
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches/com.palantir.graal/20.2.0
        key: ${{ matrix.platform }}-graalvm-20.2.0
    - name: Build with Gradle (this action caches various parts as well)
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: nativeImage
